package xmms2go

/*
We need import some enums from C.
Go should not use contents of native C directly
*/

const (
	XMMSIPCOBJECTSIGNAL = iota
	XMMSIPCOBJECTMAIN
	XMMSIPCOBJECTPLAYLIST
	XMMSIPCOBJECTCONFIG
	XMMSIPCOBJECTPLAYBACK
	XMMSIPCOBJECTMEDIALIB
	XMMSIPCOBJECTCOLLECTION
	XMMSIPCOBJECTVISUALIZATION
	XMMSIPCOBJECTMEDIAINFOREADER
	XMMSIPCOBJECTXFORM
	XMMSIPCOBJECTBINDATA
	XMMSIPCOBJECTCOLLSYNC
	XMMSIPCOBJECTCOURIER
	XMMSIPCOBJECTIPCMANAGER
	XMMSIPCOBJECTEND
)

const (
	XMMSIPCSIGNALPLAYLISTCHANGED = iota
	XMMSIPCSIGNALCONFIGVALUECHANGED
	XMMSIPCSIGNALPLAYBACKSTATUS
	XMMSIPCSIGNALPLAYBACKVOLUMECHANGED
	XMMSIPCSIGNALPLAYBACKPLAYTIME
	XMMSIPCSIGNALPLAYBACKCURRENTID
	XMMSIPCSIGNALPLAYLISTCURRENTPOS
	XMMSIPCSIGNALPLAYLISTLOADED
	XMMSIPCSIGNALMEDIALIBENTRYADDED
	XMMSIPCSIGNALMEDIALIBENTRYUPDATE
	XMMSIPCSIGNALMEDIALIBENTRYREMOVED
	XMMSIPCSIGNALCOLLECTIONCHANGED
	XMMSIPCSIGNALQUIT
	XMMSIPCSIGNALMEDIAINFOREADERSTATUS
	XMMSIPCSIGNALMEDIAINFOREADERUNINDEXED
	XMMSIPCSIGNALCOURIERMESSAGE
	XMMSIPCSIGNALIPCMANAGERCLIENTCONNECTED
	XMMSIPCSIGNALIPCMANAGERCLIENTDISCONNECTED
	XMMSIPCSIGNALEND
)

const XMMSIPCCMDFIRST = 32

const (
	XMMSIPCCMDREPLY = iota
	XMMSIPCCMDERROR
)

/* Signal subsystem methods */
const (
	XMMSIPCCMDSIGNAL = XMMSIPCCMDFIRST + iota
	XMMSIPCCMDBROADCAST
)

/* Main methods */
const (
	XMMSIPCCMDHELLO = XMMSIPCCMDFIRST + iota
	XMMSIPCCMDQUIT
	XMMSIPCCMDPLUGINLIST
	XMMSIPCCMDSTATS
)

/* Playlist methods */
const (
	XMMSIPCCMDREPLACE = XMMSIPCCMDFIRST + iota
	XMMSIPCCMDSETPOS
	XMMSIPCCMDSETPOSREL
	XMMSIPCCMDADDURL
	XMMSIPCCMDADDCOLL
	XMMSIPCCMDREMOVEENTRY
	XMMSIPCCMDMOVEENTRY
	XMMSIPCCMDLIST
	XMMSIPCCMDCURRENTPOS
	XMMSIPCCMDCURRENTACTIVE
	XMMSIPCCMDINSERTURL
	XMMSIPCCMDINSERTCOLL
	XMMSIPCCMDLOAD
	XMMSIPCCMDRADD
	XMMSIPCCMDRINSERT
)

/* Config methods */
const (
	XMMSIPCCMDGETVALUE = XMMSIPCCMDFIRST + iota
	XMMSIPCCMDSETVALUE
	XMMSIPCCMDREGVALUE
	XMMSIPCCMDLISTVALUES
)

/* playback methods */
const (
	XMMSIPCCMDSTART = XMMSIPCCMDFIRST + iota
	XMMSIPCCMDSTOP
	XMMSIPCCMDPAUSE
	XMMSIPCCMDDECODERKILL
	XMMSIPCCMDCPLAYTIME
	XMMSIPCCMDSEEKMS
	XMMSIPCCMDSEEKSAMPLES
	XMMSIPCCMDPLAYBACKSTATUS
	XMMSIPCCMDCURRENTID
	XMMSIPCCMDVOLUMESET
	XMMSIPCCMDVOLUMEGET
)

/* Medialib methods */
const (
	XMMSIPCCMDINFO = XMMSIPCCMDFIRST + iota
	XMMSIPCCMDPATHIMPORT
	XMMSIPCCMDREHASH
	XMMSIPCCMDGETID
	XMMSIPCCMDREMOVEID
	XMMSIPCCMDPROPERTYSETSTR
	XMMSIPCCMDPROPERTYSETINT
	XMMSIPCCMDPROPERTYREMOVE
	XMMSIPCCMDMOVEURL
	XMMSIPCCMDMLIBADDURL
)

/* Coll sync methods */
const (
	XMMSIPCCMDCOLLSYNCSYNC = XMMSIPCCMDFIRST + iota
)

/* Collection methods */
const (
	XMMSIPCCMDCOLLECTIONGET = XMMSIPCCMDFIRST + iota
	XMMSIPCCMDCOLLECTIONLIST
	XMMSIPCCMDCOLLECTIONSAVE
	XMMSIPCCMDCOLLECTIONREMOVE
	XMMSIPCCMDCOLLECTIONFIND
	XMMSIPCCMDCOLLECTIONRENAME
	XMMSIPCCMDQUERY
	XMMSIPCCMDQUERYINFOS
	XMMSIPCCMDIDLISTFROMPLS
)

/* bindata methods */
const (
	XMMSIPCCMDGETDATA = XMMSIPCCMDFIRST + iota
	XMMSIPCCMDADDDATA
	XMMSIPCCMDREMOVEDATA
	XMMSIPCCMDLISTDATA
)

/* visualization methods */
const (
	XMMSIPCCMDVISUALIZATIONQUERYVERSION = XMMSIPCCMDFIRST + iota
	XMMSIPCCMDVISUALIZATIONREGISTER
	XMMSIPCCMDVISUALIZATIONINITSHM
	XMMSIPCCMDVISUALIZATIONINITUDP
	XMMSIPCCMDVISUALIZATIONPROPERTY
	XMMSIPCCMDVISUALIZATIONPROPERTIES
	XMMSIPCCMDVISUALIZATIONSHUTDOWN
)

/* xform methods */
const (
	XMMSIPCCMDBROWSE = XMMSIPCCMDFIRST + iota
)

/* courier methods */
const (
	XMMSIPCCMDSENDMESSAGE = XMMSIPCCMDFIRST + iota
	XMMSIPCCMDREPLYMESSAGE
	XMMSIPCCMDGETCONNECTEDCLIENTS
)

const (
	XMMSPLAYLISTCHANGEDADD = iota
	XMMSPLAYLISTCHANGEDINSERT
	XMMSPLAYLISTCHANGEDSHUFFLE /* deprecated */
	XMMSPLAYLISTCHANGEDREMOVE
	XMMSPLAYLISTCHANGEDCLEAR /* deprecated */
	XMMSPLAYLISTCHANGEDMOVE
	XMMSPLAYLISTCHANGEDSORT /* deprecated */
	XMMSPLAYLISTCHANGEDUPDATE
	XMMSPLAYLISTCHANGEDREPLACE
)

const (
	XMMSCOLLECTIONCHANGEDADD = iota
	XMMSCOLLECTIONCHANGEDUPDATE
	XMMSCOLLECTIONCHANGEDRENAME
	XMMSCOLLECTIONCHANGEDREMOVE
)

const (
	XMMSPLAYLISTCURRENTIDFORGET = iota
	XMMSPLAYLISTCURRENTIDKEEP
	XMMSPLAYLISTCURRENTIDMOVETOFRONT
)

const (
	XMMSPLAYBACKSTATUSSTOP = iota
	XMMSPLAYBACKSTATUSPLAY
	XMMSPLAYBACKSTATUSPAUSE
)

const (
	XMMSPLAYBACKSEEKCUR = 1 + iota
	XMMSPLAYBACKSEEKSET
)

const (
	XMMSMEDIAINFOREADERSTATUSIDLE = iota
	XMMSMEDIAINFOREADERSTATUSRUNNING
)

const (
	XMMSPLUGINTYPEALL = iota
	XMMSPLUGINTYPEOUTPUT
	XMMSPLUGINTYPEXFORM
)

/* Collection type */
const (
	XMMSCOLLECTIONTYPEREFERENCE = iota
	XMMSCOLLECTIONTYPEUNIVERSE
	XMMSCOLLECTIONTYPEUNION
	XMMSCOLLECTIONTYPEINTERSECTION
	XMMSCOLLECTIONTYPECOMPLEMENT
	XMMSCOLLECTIONTYPEHAS
	XMMSCOLLECTIONTYPEMATCH
	XMMSCOLLECTIONTYPETOKEN
	XMMSCOLLECTIONTYPEEQUALS
	XMMSCOLLECTIONTYPENOTEQUAL
	XMMSCOLLECTIONTYPESMALLER
	XMMSCOLLECTIONTYPESMALLEREQ
	XMMSCOLLECTIONTYPEGREATER
	XMMSCOLLECTIONTYPEGREATEREQ
	XMMSCOLLECTIONTYPEORDER
	XMMSCOLLECTIONTYPELIMIT
	XMMSCOLLECTIONTYPEMEDIASET
	XMMSCOLLECTIONTYPEIDLIST
	XMMSCOLLECTIONTYPELAST = XMMSCOLLECTIONTYPEIDLIST
)

const (
	XMMSMEDIALIBENTRYSTATUSNEW = iota
	XMMSMEDIALIBENTRYSTATUSOK
	XMMSMEDIALIBENTRYSTATUSRESOLVING
	XMMSMEDIALIBENTRYSTATUSNOTAVAILABLE
	XMMSMEDIALIBENTRYSTATUSREHASH
)

const (
	XMMSLOGLEVELUNKNOWN = iota
	XMMSLOGLEVELFATAL
	XMMSLOGLEVELFAIL
	XMMSLOGLEVELERROR
	XMMSLOGLEVELINFO
	XMMSLOGLEVELDEBUG
	XMMSLOGLEVELCOUNT /* must be last */
)

const (
	XMMSC2CREPLYPOLICYNOREPLY = iota
	XMMSC2CREPLYPOLICYSINGLEREPLY
	XMMSC2CREPLYPOLICYMULTIREPLY
)
