package xmms2go

/*
We need import some enums from C.
Go should not use contents of native C directly
*/

const (
	XMMS_IPC_OBJECT_SIGNAL = iota
	XMMS_IPC_OBJECT_MAIN
	XMMS_IPC_OBJECT_PLAYLIST
	XMMS_IPC_OBJECT_CONFIG
	XMMS_IPC_OBJECT_PLAYBACK
	XMMS_IPC_OBJECT_MEDIALIB
	XMMS_IPC_OBJECT_COLLECTION
	XMMS_IPC_OBJECT_VISUALIZATION
	XMMS_IPC_OBJECT_MEDIAINFO_READER
	XMMS_IPC_OBJECT_XFORM
	XMMS_IPC_OBJECT_BINDATA
	XMMS_IPC_OBJECT_COLL_SYNC
	XMMS_IPC_OBJECT_COURIER
	XMMS_IPC_OBJECT_IPC_MANAGER
	XMMS_IPC_OBJECT_END
)

const (
	XMMS_IPC_SIGNAL_PLAYLIST_CHANGED = iota
	XMMS_IPC_SIGNAL_CONFIGVALUE_CHANGED
	XMMS_IPC_SIGNAL_PLAYBACK_STATUS
	XMMS_IPC_SIGNAL_PLAYBACK_VOLUME_CHANGED
	XMMS_IPC_SIGNAL_PLAYBACK_PLAYTIME
	XMMS_IPC_SIGNAL_PLAYBACK_CURRENTID
	XMMS_IPC_SIGNAL_PLAYLIST_CURRENT_POS
	XMMS_IPC_SIGNAL_PLAYLIST_LOADED
	XMMS_IPC_SIGNAL_MEDIALIB_ENTRY_ADDED
	XMMS_IPC_SIGNAL_MEDIALIB_ENTRY_UPDATE
	XMMS_IPC_SIGNAL_MEDIALIB_ENTRY_REMOVED
	XMMS_IPC_SIGNAL_COLLECTION_CHANGED
	XMMS_IPC_SIGNAL_QUIT
	XMMS_IPC_SIGNAL_MEDIAINFO_READER_STATUS
	XMMS_IPC_SIGNAL_MEDIAINFO_READER_UNINDEXED
	XMMS_IPC_SIGNAL_COURIER_MESSAGE
	XMMS_IPC_SIGNAL_IPC_MANAGER_CLIENT_CONNECTED
	XMMS_IPC_SIGNAL_IPC_MANAGER_CLIENT_DISCONNECTED
	XMMS_IPC_SIGNAL_END
)

const XMMS_IPC_CMD_FIRST = 32

const (
	XMMS_IPC_CMD_REPLY = iota
	XMMS_IPC_CMD_ERROR
)

/* Signal subsystem methods */
const (
	XMMS_IPC_CMD_SIGNAL = XMMS_IPC_CMD_FIRST + iota
	XMMS_IPC_CMD_BROADCAST
)

/* Main methods */
const (
	XMMS_IPC_CMD_HELLO = XMMS_IPC_CMD_FIRST + iota
	XMMS_IPC_CMD_QUIT
	XMMS_IPC_CMD_PLUGIN_LIST
	XMMS_IPC_CMD_STATS
)

/* Playlist methods */
const (
	XMMS_IPC_CMD_REPLACE = XMMS_IPC_CMD_FIRST + iota
	XMMS_IPC_CMD_SET_POS
	XMMS_IPC_CMD_SET_POS_REL
	XMMS_IPC_CMD_ADD_URL
	XMMS_IPC_CMD_ADD_COLL
	XMMS_IPC_CMD_REMOVE_ENTRY
	XMMS_IPC_CMD_MOVE_ENTRY
	XMMS_IPC_CMD_LIST
	XMMS_IPC_CMD_CURRENT_POS
	XMMS_IPC_CMD_CURRENT_ACTIVE
	XMMS_IPC_CMD_INSERT_URL
	XMMS_IPC_CMD_INSERT_COLL
	XMMS_IPC_CMD_LOAD
	XMMS_IPC_CMD_RADD
	XMMS_IPC_CMD_RINSERT
)

/* Config methods */
const (
	XMMS_IPC_CMD_GETVALUE = XMMS_IPC_CMD_FIRST + iota
	XMMS_IPC_CMD_SETVALUE
	XMMS_IPC_CMD_REGVALUE
	XMMS_IPC_CMD_LISTVALUES
)

/* playback methods */
const (
	XMMS_IPC_CMD_START = XMMS_IPC_CMD_FIRST + iota
	XMMS_IPC_CMD_STOP
	XMMS_IPC_CMD_PAUSE
	XMMS_IPC_CMD_DECODER_KILL
	XMMS_IPC_CMD_CPLAYTIME
	XMMS_IPC_CMD_SEEKMS
	XMMS_IPC_CMD_SEEKSAMPLES
	XMMS_IPC_CMD_PLAYBACK_STATUS
	XMMS_IPC_CMD_CURRENTID
	XMMS_IPC_CMD_VOLUME_SET
	XMMS_IPC_CMD_VOLUME_GET
)

/* Medialib methods */
const (
	XMMS_IPC_CMD_INFO = XMMS_IPC_CMD_FIRST + iota
	XMMS_IPC_CMD_PATH_IMPORT
	XMMS_IPC_CMD_REHASH
	XMMS_IPC_CMD_GET_ID
	XMMS_IPC_CMD_REMOVE_ID
	XMMS_IPC_CMD_PROPERTY_SET_STR
	XMMS_IPC_CMD_PROPERTY_SET_INT
	XMMS_IPC_CMD_PROPERTY_REMOVE
	XMMS_IPC_CMD_MOVE_URL
	XMMS_IPC_CMD_MLIB_ADD_URL
)

/* Coll sync methods */
const (
	XMMS_IPC_CMD_COLL_SYNC_SYNC = XMMS_IPC_CMD_FIRST + iota
)

/* Collection methods */
const (
	XMMS_IPC_CMD_COLLECTION_GET = XMMS_IPC_CMD_FIRST + iota
	XMMS_IPC_CMD_COLLECTION_LIST
	XMMS_IPC_CMD_COLLECTION_SAVE
	XMMS_IPC_CMD_COLLECTION_REMOVE
	XMMS_IPC_CMD_COLLECTION_FIND
	XMMS_IPC_CMD_COLLECTION_RENAME
	XMMS_IPC_CMD_QUERY
	XMMS_IPC_CMD_QUERY_INFOS
	XMMS_IPC_CMD_IDLIST_FROM_PLS
)

/* bindata methods */
const (
	XMMS_IPC_CMD_GET_DATA = XMMS_IPC_CMD_FIRST + iota
	XMMS_IPC_CMD_ADD_DATA
	XMMS_IPC_CMD_REMOVE_DATA
	XMMS_IPC_CMD_LIST_DATA
)

/* visualization methods */
const (
	XMMS_IPC_CMD_VISUALIZATION_QUERY_VERSION = XMMS_IPC_CMD_FIRST + iota
	XMMS_IPC_CMD_VISUALIZATION_REGISTER
	XMMS_IPC_CMD_VISUALIZATION_INIT_SHM
	XMMS_IPC_CMD_VISUALIZATION_INIT_UDP
	XMMS_IPC_CMD_VISUALIZATION_PROPERTY
	XMMS_IPC_CMD_VISUALIZATION_PROPERTIES
	XMMS_IPC_CMD_VISUALIZATION_SHUTDOWN
)

/* xform methods */
const (
	XMMS_IPC_CMD_BROWSE = XMMS_IPC_CMD_FIRST + iota
)

/* courier methods */
const (
	XMMS_IPC_CMD_SEND_MESSAGE = XMMS_IPC_CMD_FIRST + iota
	XMMS_IPC_CMD_REPLY_MESSAGE
	XMMS_IPC_CMD_GET_CONNECTED_CLIENTS
)

const (
	XMMS_PLAYLIST_CHANGED_ADD = iota
	XMMS_PLAYLIST_CHANGED_INSERT
	//XMMS_PLAYLIST_CHANGED_SHUFFLE /* deprecated */
	XMMS_PLAYLIST_CHANGED_REMOVE
	//XMMS_PLAYLIST_CHANGED_CLEAR /* deprecated */
	XMMS_PLAYLIST_CHANGED_MOVE
	//XMMS_PLAYLIST_CHANGED_SORT /* deprecated */
	XMMS_PLAYLIST_CHANGED_UPDATE
	XMMS_PLAYLIST_CHANGED_REPLACE
)

const (
	XMMS_COLLECTION_CHANGED_ADD = iota
	XMMS_COLLECTION_CHANGED_UPDATE
	XMMS_COLLECTION_CHANGED_RENAME
	XMMS_COLLECTION_CHANGED_REMOVE
)

const (
	XMMS_PLAYLIST_CURRENT_ID_FORGET = iota
	XMMS_PLAYLIST_CURRENT_ID_KEEP
	XMMS_PLAYLIST_CURRENT_ID_MOVE_TO_FRONT
)

const (
	XMMS_PLAYBACK_STATUS_STOP = iota
	XMMS_PLAYBACK_STATUS_PLAY
	XMMS_PLAYBACK_STATUS_PAUSE
)

const (
	XMMS_PLAYBACK_SEEK_CUR = 1 + iota
	XMMS_PLAYBACK_SEEK_SET
)

const (
	XMMS_MEDIAINFO_READER_STATUS_IDLE = iota
	XMMS_MEDIAINFO_READER_STATUS_RUNNING
)

const (
	XMMS_PLUGIN_TYPE_ALL = iota
	XMMS_PLUGIN_TYPE_OUTPUT
	XMMS_PLUGIN_TYPE_XFORM
)

/* Collection type */
const (
	XMMS_COLLECTION_TYPE_REFERENCE = iota
	XMMS_COLLECTION_TYPE_UNIVERSE
	XMMS_COLLECTION_TYPE_UNION
	XMMS_COLLECTION_TYPE_INTERSECTION
	XMMS_COLLECTION_TYPE_COMPLEMENT
	XMMS_COLLECTION_TYPE_HAS
	XMMS_COLLECTION_TYPE_MATCH
	XMMS_COLLECTION_TYPE_TOKEN
	XMMS_COLLECTION_TYPE_EQUALS
	XMMS_COLLECTION_TYPE_NOTEQUAL
	XMMS_COLLECTION_TYPE_SMALLER
	XMMS_COLLECTION_TYPE_SMALLEREQ
	XMMS_COLLECTION_TYPE_GREATER
	XMMS_COLLECTION_TYPE_GREATEREQ
	XMMS_COLLECTION_TYPE_ORDER
	XMMS_COLLECTION_TYPE_LIMIT
	XMMS_COLLECTION_TYPE_MEDIASET
	XMMS_COLLECTION_TYPE_IDLIST
	XMMS_COLLECTION_TYPE_LAST = XMMS_COLLECTION_TYPE_IDLIST
)

const (
	XMMS_MEDIALIB_ENTRY_STATUS_NEW = iota
	XMMS_MEDIALIB_ENTRY_STATUS_OK
	XMMS_MEDIALIB_ENTRY_STATUS_RESOLVING
	XMMS_MEDIALIB_ENTRY_STATUS_NOT_AVAILABLE
	XMMS_MEDIALIB_ENTRY_STATUS_REHASH
)

const (
	XMMS_LOG_LEVEL_UNKNOWN = iota
	XMMS_LOG_LEVEL_FATAL
	XMMS_LOG_LEVEL_FAIL
	XMMS_LOG_LEVEL_ERROR
	XMMS_LOG_LEVEL_INFO
	XMMS_LOG_LEVEL_DEBUG
	XMMS_LOG_LEVEL_COUNT /* must be last */
)

const (
	XMMS_C2C_REPLY_POLICY_NO_REPLY = iota
	XMMS_C2C_REPLY_POLICY_SINGLE_REPLY
	XMMS_C2C_REPLY_POLICY_MULTI_REPLY
)
