package xmms2go

const(
	XMMS_ERROR_NONE = iota
	XMMS_ERROR_GENERIC
	XMMS_ERROR_OOM
	XMMS_ERROR_PERMISSION
	XMMS_ERROR_NOENT
	XMMS_ERROR_INVAL
	XMMS_ERROR_NO_SAUSAGE
	XMMS_ERROR_COUNT /* must be last */
)

